### ISSUE TITLE
Usage example

### ISSUE THREAD

**Issue by MINDoSOFT** [antoinewdg/patch-match-opencv#1]
Hello Antoine.

Your algorithm implementation looks really interesting. I would like to use it in my master thesis. 

Can you provide an example of using your PatchMatch algorithm in OpenCV to inpaint an image?

Best regards,

Sergios.

**Comment by antoinewdg** [comment]
Hi. Thanks for your interest.
- [This file](https://github.com/antoinewdg/patch-match-opencv/blob/9de98f8b1ec408a03a9adf9bec080ec30488bd55/test/patch_match_opencv/test_patch_matcher.cpp) is an example of usage of the algorithm of an OpenCV Mat
- you can take a look at [this repo](https://github.com/antoinewdg/stylit) that is an implementationof the stylit algorithm, which itself is a slightly modified version of a (well known inpainting algorithm_[http://www.wisdom.weizmann.ac.il/~vision/VideoCompletion/SpaceTimeCompletion.pdf]
- I don't have an implementation of a pure inpainting algorithm, but with the two above points and the PatchMatch paper (that has a section about inpainting) you are on the right track :)

**Comment by MINDoSOFT** [comment]
Thank you very much for your reply.

It is really helpful for the work I am currently doing.
